chore: test

diff --git a/.github/workflows/branch-test-workflow-1.yml b/.github/workflows/branch-test-workflow-1.yml
--- a/.github/workflows/branch-test-workflow-1.yml
+++ b/.github/workflows/branch-test-workflow-1.yml
@@ -5,11 +5,14 @@ on:
 
 jobs:
   prod-check:
-    if: ${{ github.ref == 'refs/heads/main' }}
+    if: ${{ github.ref != 'refs/heads/main' }}
     runs-on: ubuntu-latest
     steps:
       - name: Check Production branch ref
-        run: echo "Deploying to production server on branch $GITHUB_REF"
+        run:
+          echo "Cannot deploy to production server from a branch different of 'main'"
+          exit 1
+        # run: echo "Deploying to production server on branch $GITHUB_REF"
   test-workflow:
     needs: [prod-check]
     uses: felipe-rastelli/github-workflow-test-repo/.github/workflows/branch-test-workflow-2.yml@develop
@@ -23,10 +26,9 @@ jobs:
         env:
           EVENT_CONTEXT: ${{ toJson(github.event) }}
         run: echo $EVENT_CONTEXT
-  post-prod-check:
-    if: ${{ github.ref != 'refs/heads/main' }}
-    runs-on: ubuntu-latest
-    steps:
-      - name: Post Check Production branch ref
-        run: echo "Cannot deploy to production server from a branch different of 'master'"
-        
+  # post-prod-check:
+  #   if: ${{ github.ref != 'refs/heads/main' }}
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Post Check Production branch ref
+  #       run: echo "Cannot deploy to production server from a branch different of 'master'"
