chore: test

diff --git a/.github/workflows/branch-test-workflow-1.yml b/.github/workflows/branch-test-workflow-1.yml
--- a/.github/workflows/branch-test-workflow-1.yml
+++ b/.github/workflows/branch-test-workflow-1.yml
@@ -4,17 +4,16 @@ on:
   workflow_dispatch:
 
 jobs:
-  prod-check:
-    if: ${{ github.ref != 'refs/heads/main' }}
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check Production branch ref
-        run: |
-          echo "Cannot deploy to production server from a branch different of 'main'"
-          exit 1
-        # run: echo "Deploying to production server on branch $GITHUB_REF"
+  # prod-check:
+  #   if: ${{ github.ref != 'refs/heads/main' }}
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check Production branch ref
+  #       run: |
+  #         echo "Cannot deploy to production server from a branch different of 'main'"
+  #         exit 1
   test-workflow:
-    needs: [prod-check]
+    # needs: [prod-check]
     uses: felipe-rastelli/github-workflow-test-repo/.github/workflows/branch-test-workflow-2.yml@feature/feat1
   test-steps1:
     needs: [test-workflow]
